# Secret CONTAINERS. No secret VALUES.
#
# ==================================================================================================
# Terraform creates each `aws_secretsmanager_secret` and deliberately creates NO
# `aws_secretsmanager_secret_version` for any of them.
# ==================================================================================================
#
# This is the whole design, and the reason is mechanical rather than stylistic: Terraform records
# every managed attribute in state, in plaintext, forever. A secret value passed through a variable,
# read from a file, or generated by `random_password` ends up in the state file and in every plan
# output that touches it. "The state bucket is encrypted and private" is true and is not the same
# thing as "the secret is not written down in a second place".
#
# So Terraform owns the container -- its name, its ARN, its rotation policy, its recovery window,
# and the IAM that lets exactly one role read it -- and a human writes the value once, out of band:
#
#     aws secretsmanager put-secret-value \
#       --secret-id pronto/production/jwt-secret \
#       --secret-string "$(openssl rand -base64 48)"
#
# The runbook has the full procedure. Until a version exists the ECS task will fail to start with a
# ResourceNotFoundException naming the secret, which is the correct failure: loud, specific, and
# before the port is bound.
#
# The RDS MASTER password is not here at all -- database.tf uses manage_master_user_password, so RDS
# generates and owns it in a secret of its own. What is here is the password for the least-privilege
# application role.

locals {
  secret_prefix = "${var.project}/${var.environment_name}"

  # One place that knows the full set, so iam.tf can grant read access to exactly these ARNs and
  # compute.tf can inject exactly these, without either drifting from the other.
  application_secrets = {
    db_password    = "db-app-password"
    jwt_secret     = "jwt-secret"
    otp_pepper     = "otp-pepper"
    openai_api_key = "openai-api-key"
    maps_api_key   = "maps-api-key"
  }
}

resource "aws_secretsmanager_secret" "application" {
  for_each = local.application_secrets

  name        = "${local.secret_prefix}/${each.value}"
  description = local.secret_descriptions[each.key]

  # Seven days of "deleted but recoverable". Zero would mean an accidental delete is instant and
  # final; 30 (the AWS default) means a name cannot be reused for a month, which turns a rebuild of
  # this stack into a naming problem.
  recovery_window_in_days = 7

  tags = { Name = "${local.secret_prefix}/${each.value}" }
}

locals {
  secret_descriptions = {
    db_password = "PostgreSQL password for the least-privilege application role (${var.db_app_username}). NOT the RDS master password -- RDS owns that one itself."

    jwt_secret = "HS256 signing key for every session token this API issues. >= 32 characters. Rotating it invalidates every logged-in session."

    # The pepper and the JWT secret are deliberately two secrets rather than one. application.yml's
    # pronto.otp.pepper comment gives the reason: different blast radii, and rotating one must not
    # force rotating the other. JwtSecretStartupGuard and ProductionHardeningStartupGuard each check
    # their own, and MS4's variable table requires them to differ.
    otp_pepper = "Server-side HMAC key protecting stored one-time passwords. >= 32 characters, and MUST be a different value from jwt-secret. Rotating it invalidates outstanding OTP challenges."

    openai_api_key = "OpenAI API key. Required whenever AI_MODE=openai, which AiModeStartupGuard requires in production."

    maps_api_key = "Google Maps Platform key, restricted to the Geocoding API and the Routes API and to this deployment's egress addresses. Must NOT be the development key used for MS2 validation."
  }
}
